# Kanagawa Wave colour palette
# https://github.com/rebelot/kanagawa.nvim
set -g @theme-bg "#1F1F28"
set -g @theme-fg "#16161D"
set -g @theme-muted "#54546D"
set -g @theme-border "#2A2A37"
set -g @theme-accent "#727169"
set -g @theme-accent-fg "#1F1F28"
