# Nord colour palette
# https://www.nordtheme.com/docs/colors-and-palettes
set -g @theme-bg "#2E3440"
set -g @theme-fg "#D8DEE9"
set -g @theme-muted "#4C566A"
set -g @theme-border "#434C5E"
set -g @theme-accent "#88C0D0"
set -g @theme-accent-fg "#2E3440"
